export enum ErrorCode {
    USER_NOT_FOUND = 'USER_NOT_FOUND',
    USER_EMAIL_EXISTS = 'USER_EMAIL_EXISTS',
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}
